# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('acerequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCreateView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.views.generic.edit.CreateView),
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='comments',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='max_payload',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
