# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acerequests', '0003_auto_20170324_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.CharField(max_length=50)),
                ('to_airport', models.CharField(max_length=50)),
                ('aircraft_type', models.CharField(choices=[('NILL', 'No Preference'), ('A300', 'Airbus A300'), ('A310', 'Airbus A310'), ('A320', 'Airbus A320'), ('A330', 'Airbus A330'), ('AN12', 'Antonov AN12'), ('AN26', 'Antonov AN26'), ('AN32', 'Antonov AN32'), ('AN124', 'Antonov AN124'), ('AN225', 'Antonov AN225'), ('B727', 'Boeing 727'), ('B737', 'Boeing 737'), ('B747', 'Boeing 747'), ('B747-8', 'Boeing 747-8'), ('B757', 'Boeing 757'), ('B767', 'Boeing 767'), ('B777', 'Boeing 777'), ('Dash8', 'Bombardier Dash-8'), ('BAE146QT', 'British Aerospace 146QT'), ('BAEATPF', 'British Aerospace ATPF'), ('DC3', 'Douglas DC-3'), ('DC8', 'Douglas DC-8'), ('DC9', 'Douglas DC-9'), ('IL76', 'Ilyushin IL76'), ('IL96', 'Ilyushin IL96'), ('L100', 'Lockheed L100'), ('DC10', 'McDonnell Douglas DC10'), ('DC11', 'McDonnell Douglas DC11'), ('TU204', 'Tupolev TU204'), ('C208', 'Cessna Caravan'), ('LET410', 'LET 410'), ('SD330', 'Short 300'), ('ATR42', 'ATR 42'), ('ATR72', 'ATR 72'), ('Other', 'Other')], max_length=26)),
                ('max_payload', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(200000), django.core.validators.MinValueValidator(1)])),
                ('max_volume', models.CharField(blank=True, max_length=50)),
                ('date_required', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('cargo_type', models.CharField(choices=[('auto_parts', 'Automotive & Aeronautical Spare Parts'), ('election_materials', 'Election Materials'), ('general', 'General Cargo'), ('hazardous', 'Hazardous Materials'), ('humanitarian', 'Humanitarian & Relief Cargo'), ('live_stock', 'Live Stock'), ('luxury', 'Luxury Goods'), ('military', 'Military Support Equipment'), ('musical_band', 'Musical Band Tours'), ('oil_gas', 'Oil & Gas\xa0Industry Equipment'), ('perishable', 'Perishable Goods'), ('security_sensitive', 'Security Sensitive Monetary Cargo'), ('telecom_equipment', 'Telecommunications Equipment'), ('other', 'Other')], max_length=26)),
                ('cargo_nature', models.CharField(blank=True, choices=[('normal', 'Normal'), ('over_weight', 'Over Weight'), ('time_sensitive', 'Time Sensitive')], max_length=26)),
                ('number_pallets', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)])),
                ('comments', models.TextField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='aircraftavailability',
            name='max_payload',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(200000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
